### PR TITLE
Initial readme

### LINKED ISSUE #4: Missing readme or something similar with project idea/goals description
I am watching this project by default as a new OS initiative in 4Finance IT, but for a newcomer it is kinda hard to grasp what is this project about without any readme or something similar :)

### PR DESCRIPTION
**Pull request by tadaskay**
Hopefully resolves #4 

Markdown view: https://github.com/tadaskay/featuros/blob/documentation-init/README.md

### CODE REVIEW

**Comment by mvaitkus** [comment]
Looks nice given current status of the project. The things I would consider adding:
1. What data are we planning to store and explain the fields (name, product, group, version)
2. We have a licence file, but maybe we should also have a notice about it in the readme.

**Comment by tadaskay** [comment]
It makes perfect sense to add these things. 

Let's talk about documenting metadata though. I could think of at least 3 places where to add it:
1. This main project README
2. `featuros-gradle-plugin` README
3. Wiki/docs

To avoid duplicating things, we should decide where we place it. What do you think?

**Comment by mvaitkus** [comment]
As we discussed offline, let's use following structure for main readme:
Featuros
Install
Usage (without plugins, how to post notification from command line)
Plugins (data similar to current How It Works, just add links to plugin readmes)
Run the sample
Modules
Project Goals
License

Regarding the metadata documentation  - it should probably go to wiki. Let's keep documentation for quickstart usecases in readmes and we can go deeper in wiki.

**Comment by askindaras** [comment]
Nice job guys. Keep going!

**Pull request merged**
